name: ${project.artifactId}
version: ${project.version}
main: ru.mrimax.PGMoneyEntity
api-version: 1.16
description: //Описание
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.3.10"
author: MriMax